version: '3'
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: imageprocessing-jupyter
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /work --ip=0.0.0.0 --allow-root
  lab:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: imageprocessing-lab
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /work --ip=0.0.0.0 --allow-root
  julia:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: imageprocessing-julia
    volumes:
      - ./:/work
    working_dir: /work
    command: julia --project=/work
